---
title: "SNAP Penetration Rate by Tract, by Ethnicity"
author: "Koller Adzick, Allen Hu, Katherine Li, Jessica Lin"
output: pdf_document
---
## Read & Clean Data
```{r,message=FALSE, warning=FALSE}
library(tidyr)
library(HH)
library(tidyverse)
snap_analysis <- read.csv("~/Downloads/snap_analysis.csv", stringsAsFactors=TRUE)

# select the wanted columns/variables:
newdf<-snap_analysis[c('elig_month','tract','race_ethnicity','snap_perc_by_adjusted_income')]

# select latest snap performance availabie:
newdata <- newdf[ which(newdf['elig_month']=='2019-12-01'), ]

# change data from long to wide:
dfw<- spread(newdata, race_ethnicity, snap_perc_by_adjusted_income)

# add a new column - 'race_sums' aggregates SNAP rates for all races in that tract and use this column as a
# cratirie for ranking the graph below
dfw$race_sums <- rowSums(dfw[,c('American Indian or Alaskan Native','Asian/Pacific Islander','Black/African American','Hispanic or Latino','Other or Unknown','White')], na.rm = TRUE)
df<-dfw %>% arrange(desc(race_sums))
df11<-df[c('tract','American Indian or Alaskan Native','Asian/Pacific Islander','Black/African American','Hispanic or Latino','Other or Unknown','White','race_sums')]
df1=df11[,-8]
```

## Graph SNAP rate by race by each tract, ordered from highest penatration to the lowest:
```{r,fig.dim = c(18, 132)}
HH::likert(tract ~ ., df1, main="How is your tract doing on SNAP penetration rate \nmost recently (Dec 2019)?", xlab='percent',positive.order=TRUE,col=c("aliceblue","antiquewhite","light blue","coral2","bisque4","darkseagreen"))
```


## Top 20 tracts:
```{r,fig.dim = c(13, 10)}
  HH::likert(tract ~ ., df1[c(1:20),], main="Best 20 penetrated tracts  \nmost recent data (2019-12)", xlab='penetration rate',positive.order=TRUE,col=c("aliceblue","antiquewhite","light blue","coral2","bisque4","darkseagreen"))
```


## Bottom 20 tracts:
```{r,fig.dim = c(13, 10)}

df2<-df1[c(266:286),]
  HH::likert(tract ~ ., df2, main="Worst 20 penetrated tracts  \nmost recent data (2019-12)", xlab='penetration rate',positive.order=TRUE,col=c("aliceblue","orange","light blue","coral2","bisque4","darkseagreen"))
```